image: ubuntu/lts
shell: true
packages:
  - ruby
  - ruby-dev
sources:
  - hg+https://hg.sr.ht/~mahlon/ruby-mdbx
tasks:
  - env-setup: |
      git clone https://github.com/erthink/libmdbx.git
      cd libmdbx
      make dist
      cd dist
      make
      sudo make install
  - project-setup: |
      cd ~/ruby-mdbx
      sudo gem install -Ng
  - test: |
      sudo locale-gen en_US.UTF-8
      sudo update-locale LANG=en_US.UTF-8
      export LC_ALL=en_US.UTF-8
      cd ~/ruby-mdbx
      rake test
triggers:
  - action: email
    condition: always
    to: mahlon@martini.nu

